dataset_params:
  im_path: 'img_align_celeba'
  im_ext : 'jpg'
  im_channels : 3
  im_size : 64
  name : 'celeb'

model_params:
  latent_dim : 100
  generator_channels : [ 1024, 512, 256, 128 ]
  generator_kernels : [ 4,4,4,4,4 ]
  generator_strides : [ 2,2,2,2,2 ]
  generator_paddings : [ 0,1,1,1,1 ]
  generator_output_paddings : [ 0,0,0,0,0 ]
  discriminator_channels: [ 128, 256, 512, 1024 ]
  discriminator_kernels: [ 4,4,4,4,4 ]
  discriminator_strides: [ 2,2,2,2,2 ]
  discriminator_paddings: [ 1,1,1,1,0 ]

train_params:
  task_name: 'task_celeb'
  batch_size: 64
  num_epochs: 4
  num_samples : 100
  num_grid_rows : 10
  save_sample_steps : 200
  lr: 0.0005
  ckpt_name: 'celeb_ckpt.pth'
