dataset_params:
  im_path: 'data/train/images'
  im_ext : 'png'
  im_channels : 3
  im_size : 28
  name : 'mnist'

model_params:
  latent_dim : 100
  generator_channels : [ 512, 256, 128 ]
  generator_kernels : [ 4,4,4,4 ]
  generator_strides : [ 2,2,2,2 ]
  generator_paddings : [ 1,1,1,1 ]
  generator_output_paddings : [ 1,1,0,0 ]
  discriminator_channels : [ 128, 256, 512 ]
  discriminator_kernels : [ 4,4,4,4 ]
  discriminator_strides : [ 2,2,2,2 ]
  discriminator_paddings : [ 1,1,1,1 ]

train_params:
  task_name: 'task_mnist_colored'
  batch_size: 64
  num_epochs: 20
  num_samples : 100
  num_grid_rows : 10
  save_sample_steps : 50
  lr: 0.0005
  ckpt_name: 'mnist_colored_ckpt.pth'
